import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ankit',
      email: 'ankit@gmail.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike T-Shirt',
      slug: 'nike-t-shirt',
      category: 'Shirts',
      image: '/images/n1.jpg',
      price: 400,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas T-Shirt',
      slug: 'adidas-t-shirt',
      category: 'Shirts',
      image: '/images/a1.jpg',
      price: 350,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Puma T-Shirt',
      slug: 'puma-t-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 400,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Reebok T-Shirt',
      slug: 'reebok-t-shirt',
      category: 'Shirts',
      image: '/images/r1.jpg',
      price: 250,
      countInStock: 2,
      brand: 'Reebok',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Baseball Jacket',
      slug: 'jacket-1',
      category: 'Jacket',
      image: '/images/j1.jpeg',
      price: 5999,
      countInStock: 1,
      brand: 'h&m',
      rating: 4.5,
      numReviews: 10,
      description:
        'Baseball jacket in soft, felted fabric with lightly padded sleeves in a contrasting colour. Regular fit with press-studs down the front and welt front pockets with a press-stud. Small, ribbed stand-up collar and matching ribbing at the cuffs and hem. Inner pocket with a press-stud. Quilted lining.',
    },
    {
      name: 'Regular Fit Denim Jacket',
      slug: 'jacket-2',
      category: 'Jacket',
      image: '/images/j2.jpeg',
      price: 2999,
      countInStock: 10,
      brand: 'h&m',
      rating: 4.5,
      numReviews: 10,
      description:
        'Regular-fit jacket in rigid denim with a collar, metal buttons down the front, flap chest pockets with a button and welt side pockets. Long sleeves, buttoned cuffs and an adjustable tab and buttons at the sides.',
    },
    {
      name: 'Lightweight Puffer Jacket',
      slug: 'jacket-3',
      category: 'Jacket',
      image: '/images/j3.jpeg',
      price: 2999,
      countInStock: 10,
      brand: 'h&m',
      rating: 4.5,
      numReviews: 10,
      description:
        'Lightweight puffer jacket in woven fabric with a hood and discreet zip down the front with a chin guard. Pockets in the side seams with a concealed zip, and narrow elastication at the cuffs and hem. Unlined.',
    },
    {
      name: 'Relaxed Fit Fleece Jacket',
      slug: 'jacket-4',
      category: 'Jacket',
      image: '/images/j4.jpeg',
      price: 3999,
      countInStock: 2,
      brand: 'h&m',
      rating: 4.5,
      numReviews: 10,
      description:
        'Relaxed-fit jacket in soft fleece with a nylon stand-up collar and zip down the front. Zipped flap chest pocket in nylon with a hook and loop fastening, and discreet pockets in the side seams. Unlined.',
    },
    {
      name: 'Nike Lower',
      slug: 'nike-lower',
      category: 'Lower',
      image: '/images/n2.jpg',
      price: 700,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Lower',
      slug: 'adidas-lower',
      category: 'Lower',
      image: '/images/a2.jpg',
      price: 650,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Puma Lower',
      slug: 'puma-lower',
      category: 'Lower',
      image: '/images/p2.jpg',
      price: 500,
      countInStock: 0,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Reebok Lower',
      slug: 'reebok-lower',
      category: 'Lower',
      image: '/images/r2.jpg',
      price: 450,
      countInStock: 5,
      brand: 'Reebok',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Shoes',
      slug: 'nike-shoes',
      category: 'Shoes',
      image: '/images/n3.jpg',
      price: 1200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Shoes',
      slug: 'adidas-shoes',
      category: 'Shoes',
      image: '/images/a3.jpg',
      price: 1100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Puma Shoes',
      slug: 'puma-shoes',
      category: 'Shoes',
      image: '/images/p3.jpg',
      price: 1300,
      countInStock: 15,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Reebok Shoes',
      slug: 'reebok-shoes',
      category: 'Shoes',
      image: '/images/r3.jpg',
      price: 1150,
      countInStock: 0,
      brand: 'Reebok',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Iphone 14 pro max',
      slug: 'iphone-14',
      category: 'Phones',
      image: '/images/g1.webp',
      price: 149900,
      countInStock: 1,
      brand: 'Iphone',
      rating: 4.5,
      numReviews: 10,
      description: 'Apple iPhone 14 Pro Max (256 GB) - Gold',
    },
    {
      name: 'Iphone 14 pro',
      slug: 'iphone-13',
      category: 'Phones',
      image: '/images/g2.webp',
      price: 127999,
      countInStock: 5,
      brand: 'Iphone',
      rating: 4.5,
      numReviews: 10,
      description: 'Apple iPhone 14 (128 GB) - Midnight',
    },

    {
      name: 'Iphone 12',
      slug: 'iphone-11',
      category: 'Phones',
      image: '/images/g3.webp',
      price: 59900,
      countInStock: 3,
      brand: 'Iphone',
      rating: 4.5,
      numReviews: 10,
      description: 'Apple iPhone 12 (64GB) - Blue',
    },
    {
      name: 'Iphone 11',
      slug: 'iphone-10',
      category: 'Phones',
      image: '/images/g4.webp',
      price: 48900,
      countInStock: 5,
      brand: 'Iphone',
      rating: 4.5,
      numReviews: 10,
      description: 'Apple iPhone 11 (128GB) - White',
    },
    {
      name: 'Airdopes 141',
      slug: 'buds-1',
      category: 'Earphones',
      image: '/images/e1.webp',
      price: 1299,
      countInStock: 10,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Airdopes 141 |  Wireless Earbuds with 8mm drivers, Upto 42 Hours Playback, ENx™ Technology, IPX4 Water Resistance',
    },
    {
      name: 'Airdopes 161',
      slug: 'buds-2',
      category: 'Earphones',
      image: '/images/e2.webp',
      price: 1099,
      countInStock: 5,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Airdopes 161 |  Wireless Earbuds with Massive Playback of upto 17 Hour, IPX5 Water & Sweat Resistance, IWP Technology, Type C Interface',
    },

    {
      name: 'Airdopes 181',
      slug: 'buds-3',
      category: 'Earphones',
      image: '/images/e3.webp',
      price: 1499,
      countInStock: 3,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Airdopes 181 |  Wireless Earbuds with 10mm Driver, Type C Interface, BEAST™ Mode & Voice Assistant, ENx Technology',
    },
    {
      name: 'Airdopes 141 pro',
      slug: 'buds-4',
      category: 'Earphones',
      image: '/images/e4.webp',
      price: 1599,
      countInStock: 5,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Airdopes 141 Pro |  12mm Drivers, Upto 45 Hours Playback, Quad Mics with ENx™️ Technology',
    },
    {
      name: 'Wave Call',
      slug: 'watch-1',
      category: 'Smart Watch',
      image: '/images/s1.webp',
      price: 1799,
      countInStock: 5,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Wave Call |  Bluetooth Calling Smartwatch with 1.69" (4.29 cm) HD Curved Display, 150+ Watch Faces, Heart Rate & SPO2 Monitoring',
    },
    {
      name: 'Wave Leap Call',
      slug: 'watch-2',
      category: 'Smart Watch',
      image: '/images/s2.webp',
      price: 2199,
      countInStock: 5,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Wave Leap Call |  Premium Bluetooth Calling Smartwatch with 1.83" (4.64 cm) HD Display, 100+ Sports Modes, 10 Days Of Battery Life',
    },
    {
      name: 'Lunar Connect ',
      slug: 'watch-3',
      category: 'Smart Watch',
      image: '/images/s3.webp',
      price: 2499,
      countInStock: 5,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Lunar Connect |  Round Dial Smart Watch with 1.28” (3.25 cm) HD Display, BT Calling, Supports Hindi & English Language, Up to 20 contacts, 100+ Sports Modes',
    },
    {
      name: 'Lunar Call Pro',
      slug: 'watch-4',
      category: 'Smart Watch',
      image: '/images/s4.webp',
      price: 4299,
      countInStock: 5,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Lunar Call Pro |  Round Dial Smart Watch with 1.39" (3.53 cms) Big AMOLED Display, SensAi, Watch Face Studio, Bluetooth Calling, 700+ Active Modes, Apollo3.5 Blue Plus Processor',
    },
    {
      name: 'Aavante Baar 610',
      slug: 'bar-1',
      category: 'Soundbar',
      image: '/images/b1.webp',
      price: 1999,
      countInStock: 5,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Aavante Bar 610 |  25W Bluetooth Soundbar with 7 Hours Battery Backup, 2.0 Channel, Dual Passive Radiators, Carry & Connect With Ease, BT, AUX',
    },
    {
      name: 'Aavante Baar 1150',
      slug: 'bar-2',
      category: 'Soundbar',
      image: '/images/b2.webp',
      price: 5299,
      countInStock: 50,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Aavante Bar 1150 |  Home Theater Sound Bar with 60W Sound Output, 2.0 Channel, Bluetooth,AUX, USB Compatible',
    },
    {
      name: 'Aavante Baar 1198',
      slug: 'bar-3',
      category: 'Soundbar',
      image: '/images/b3.webp',
      price: 6299,
      countInStock: 0,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Aavante Bar 1198 |  2.2 Channel Bluetooth Sound Bar with 90W RMS, Entertainment EQ modes, AUX, USB compatible',
    },
    {
      name: 'Aavante Baar 1500N',
      slug: 'bar-4',
      category: 'Soundbar',
      image: '/images/b4.webp',
      price: 10499,
      countInStock: 10,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 10,
      description:
        'boAt Aavante Bar 1500N |  Best Bluetooth 160W Home Theatre with 2.1 Channel Sound, Multiple EQ Modes, USB, AUX, HDMI(ARC)',
    },
  ],
};
export default data;
